import React from 'react';
import { Landmark, Check, X, Printer, FileText, Sparkles, Plus, ExternalLink } from 'lucide-react';

export default function Comparison({ bilingual, compareList, toggleCompare, schemes, setPage }) {
  const handlePrint = () => {
    window.print();
  };

  // Translations dictionary
  const t = {
    title: bilingual === 'EN' ? 'Scheme Comparison Tool' : 'పథకాల పోలిక పరికరం',
    subtitle: bilingual === 'EN' ? 'Compare up to 3 central and state schemes side-by-side to understand eligibility, benefits, and documents.' : 'అర్హతలు, ప్రయోజనాలు మరియు పత్రాలను అర్థం చేసుకోవడానికి గరిష్టంగా 3 కేంద్ర మరియు రాష్ట్ర పథకాలను పక్కపక్కన పోల్చండి.',
    printReport: bilingual === 'EN' ? 'Print / Export PDF Report' : 'రిపోర్ట్‌ను ప్రింట్ / PDF కి ఎగుమతి చేయి',
    noSchemesTitle: bilingual === 'EN' ? 'No Schemes Selected' : 'ఎటువంటి పథకాలు ఎంపిక కాలేదు',
    noSchemesSubtitle: bilingual === 'EN' ? 'Go to the Schemes Database or Eligibility Checker and click the comparison button (+) on schemes to add them here.' : 'పథకాల డేటాబేస్ లేదా అర్హత పరిశీలనకు వెళ్లి, పథకాలను ఇక్కడ జోడించడానికి వాటిపై ఉన్న పోలిక బటన్ (+) క్లిక్ చేయండి.',
    browseSchemes: bilingual === 'EN' ? 'Browse Schemes Database' : 'పథకాల డేటాబేస్ బ్రౌజ్ చేయి',
    selectAnotherTitle: bilingual === 'EN' ? 'Select Another Scheme' : 'మరో పథకాన్ని ఎంచుకోండి',
    selectAnotherSubtitle: (name) => bilingual === 'EN' 
      ? `You have selected ${name}. Please select at least one more scheme to perform a comparison.`
      : `మీరు ${name} పథకాన్ని ఎంచుకున్నారు. పోలికను ప్రారంభించడానికి కనీసం మరొక పథకాన్ని ఎంచుకోండి.`,
    suggestedSimilar: bilingual === 'EN' ? 'Suggested Similar Schemes:' : 'సరిపోయే ఇతర పథకాల సూచనలు:',
    addBtn: bilingual === 'EN' ? 'Add' : 'జోడించు',
    browseMore: bilingual === 'EN' ? 'Browse More Schemes' : 'మరిన్ని పథకాలు బ్రౌజ్ చేయి',
    highlightNote: bilingual === 'EN' 
      ? 'Rows highlighted in soft orange indicate different parameters. Rows in white indicate matching constraints. The star (⭐) flags the recommended scheme.'
      : 'లేత నారింజ రంగులో హైలైట్ చేయబడిన అడ్డు వరుసలు విభిన్న పారామితులను సూచిస్తాయి. తెలుపు రంగులో ఉన్నవి సరిపోలిన వివరాలు. నక్షత్రం (⭐) సిఫార్సు చేయబడిన పథకాన్ని సూచిస్తుంది.',
    parametersColumn: bilingual === 'EN' ? 'Parameters' : 'పారామితులు',
    recommendedScheme: bilingual === 'EN' ? '⭐ Recommended Scheme' : '⭐ సిఫార్సు చేయబడిన పథకం',
    reportWatermark: (dateStr) => bilingual === 'EN'
      ? `Report generated by Unified Government Services Portal. Printed on: ${dateStr}.`
      : `రిపోర్ట్ సమన్వయ ప్రభుత్వ సేవల పోర్టల్ ద్వారా రూపొందించబడింది. ముద్రించిన తేదీ: ${dateStr}.`,
    paramLabels: {
      category_name: bilingual === 'EN' ? 'Scheme Category' : 'పథకం వర్గం',
      department_name: bilingual === 'EN' ? 'Administrative Department' : 'పరిపాలనా విభాగం',
      financial_assistance_amount: bilingual === 'EN' ? 'Financial Assistance' : 'ఆర్థిక సహాయం',
      description: bilingual === 'EN' ? 'Scheme Purpose' : 'పథకం ఉద్దేశం',
      benefits: bilingual === 'EN' ? 'Welfare Benefits' : 'సంక్షేమ ప్రయోజనాలు',
      eligibility_criteria: bilingual === 'EN' ? 'Detailed Eligibility' : 'వివరణాత్మక అర్హత',
      min_income: bilingual === 'EN' ? 'Income Limit constraints' : 'ఆదాయ పరిమితి నిబంధనలు',
      min_age: bilingual === 'EN' ? 'Age Requirements' : 'వయస్సు నిబంధనలు',
      gender_restriction: bilingual === 'EN' ? 'Gender Requirements' : 'లింగ నిబంధనలు',
      required_documents: bilingual === 'EN' ? 'Required Documents' : 'అవసరమైన పత్రాలు',
      application_process: bilingual === 'EN' ? 'Application Process' : 'దరఖాస్తు విధానం',
      processing_time: bilingual === 'EN' ? 'Expected Processing Time' : 'అంచనా ప్రక్రియ సమయం',
      official_website: bilingual === 'EN' ? 'Official Website link' : 'అధికారిక వెబ్‌సైట్ లింక్',
      contact_details: bilingual === 'EN' ? 'Helpline Contact' : 'సహాయ కేంద్రం నంబర్'
    },
    centralScheme: bilingual === 'EN' ? 'Central Scheme' : 'కేంద్ర పథకం',
    stateScheme: bilingual === 'EN' ? 'State Scheme' : 'రాష్ట్ర పథకం',
    aidYear: (amt) => bilingual === 'EN' ? `₹${amt.toLocaleString('en-IN')} / year` : `సంవత్సరానికి ₹${amt.toLocaleString('en-IN')}`,
    serviceBenefits: bilingual === 'EN' ? 'Service Benefits / Subsidies' : 'సేవా ప్రయోజనాలు / సబ్సిడీలు',
    maxIncomeLimit: (amt) => bilingual === 'EN' ? `Max Income: ₹${amt.toLocaleString('en-IN')}` : `గరిష్ట ఆదాయం: ₹${amt.toLocaleString('en-IN')}`,
    noIncomeRestriction: bilingual === 'EN' ? 'No Income restrictions' : 'ఆదాయ పరిమితులు లేవు',
    ageRange: (min, max) => bilingual === 'EN' ? `${min} to ${max} Years` : `${min} నుండి ${max} సంవత్సరాలు`,
    allGendersEligible: bilingual === 'EN' ? 'All Genders Eligible' : 'అన్ని లింగాల వారికి అర్హత ఉంది',
    genderOnly: (gender) => {
      const g = gender === 'Male' ? (bilingual === 'EN' ? 'Male' : 'పురుషులు') : (bilingual === 'EN' ? 'Female' : 'స్త్రీలు');
      return bilingual === 'EN' ? `${gender} only` : `${g} మాత్రమే`;
    }
  };

  // Check if rows are different to highlight
  const isRowDifferent = (paramKey) => {
    if (compareList.length < 2) return false;
    const firstVal = compareList[0][paramKey];
    return compareList.some(item => String(item[paramKey]) !== String(firstVal));
  };

  // Find the recommended scheme (highest financial assistance)
  const getRecommendedSchemeId = () => {
    if (compareList.length === 0) return null;
    let maxAid = -1;
    let recommendedId = null;
    compareList.forEach(s => {
      const aid = parseFloat(s.financial_assistance_amount) || 0;
      if (aid > maxAid) {
        maxAid = aid;
        recommendedId = s.id;
      }
    });
    return recommendedId;
  };

  const recommendedId = getRecommendedSchemeId();

  // Find related suggestions
  const getSuggestions = () => {
    if (compareList.length === 0) return [];
    // Suggest schemes of the same category as the first compared scheme, excluding already compared ones
    const catId = compareList[0].category_id;
    return schemes.filter(s => 
      s.category_id === catId && 
      !compareList.some(comp => comp.id === s.id)
    ).slice(0, 3);
  };

  const suggestions = getSuggestions();

  return (
    <div className="space-y-6 pb-12">
      {/* Header Panel */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 no-print">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2">
            <span className="w-1.5 h-8 bg-gov-blue rounded-full"></span>
            {t.title}
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
            {t.subtitle}
          </p>
        </div>

        {compareList.length >= 2 && (
          <button
            onClick={handlePrint}
            className="bg-gov-blue hover:bg-gov-navy text-white px-5 py-2.5 rounded-xl font-semibold text-xs flex items-center gap-2 transition shadow-sm"
          >
            <Printer className="w-4 h-4" /> {t.printReport}
          </button>
        )}
      </div>

      {compareList.length === 0 ? (
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-12 text-center rounded-3xl max-w-lg mx-auto flex flex-col items-center">
          <FileText className="w-12 h-12 text-slate-300 dark:text-slate-700 mb-4" />
          <h3 className="font-bold text-slate-900 dark:text-white text-lg">{t.noSchemesTitle}</h3>
          <p className="text-xs text-slate-400 mt-2 max-w-xs leading-relaxed">
            {t.noSchemesSubtitle}
          </p>
          <button
            onClick={() => setPage('schemes')}
            className="mt-6 bg-gov-blue hover:bg-gov-navy text-white text-xs font-bold py-2.5 px-6 rounded-xl transition"
          >
            {t.browseSchemes}
          </button>
        </div>
      ) : compareList.length === 1 ? (
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-12 text-center rounded-3xl max-w-lg mx-auto flex flex-col items-center">
          <Sparkles className="w-12 h-12 text-gov-gold mb-4" />
          <h3 className="font-bold text-slate-900 dark:text-white text-lg">{t.selectAnotherTitle}</h3>
          <p className="text-xs text-slate-400 mt-2 max-w-xs leading-relaxed">
            {t.selectAnotherSubtitle(compareList[0].name)}
          </p>
          
          {/* Direct Category suggestion */}
          {suggestions.length > 0 && (
            <div className="w-full mt-6 space-y-3">
              <span className="text-[10px] uppercase font-bold text-slate-400 block tracking-wider">{t.suggestedSimilar}</span>
              <div className="grid grid-cols-1 gap-2">
                {suggestions.map(s => (
                  <button
                    key={s.id}
                    onClick={() => toggleCompare(s)}
                    className="flex justify-between items-center text-left p-3 bg-slate-50 hover:bg-slate-100 dark:bg-slate-800 rounded-xl border border-slate-200/50 dark:border-slate-700/60 transition w-full"
                  >
                    <span className="font-bold text-slate-900 dark:text-white text-xs truncate max-w-[200px]">{s.name}</span>
                    <span className="text-[10px] text-gov-blue font-bold flex items-center gap-1">{t.addBtn} <Plus className="w-3.5 h-3.5" /></span>
                  </button>
                ))}
              </div>
            </div>
          )}

          <button
            onClick={() => setPage('schemes')}
            className="mt-6 bg-gov-blue hover:bg-gov-navy text-white text-xs font-bold py-2.5 px-6 rounded-xl transition"
          >
            {t.browseMore}
          </button>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Mobile responsive comparison helper note */}
          <div className="p-4 bg-amber-50 dark:bg-amber-950/20 text-amber-800 dark:text-amber-300 rounded-2xl border border-amber-200/50 dark:border-amber-900/30 text-xs flex items-center gap-2 no-print">
            <Sparkles className="w-5 h-5 flex-shrink-0" />
            <span>{t.highlightNote}</span>
          </div>

          {/* Comparison Table Grid */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-3xl overflow-hidden shadow-sm">
            <div className="overflow-x-auto">
              <table className="w-full table-fixed min-w-[700px] border-collapse text-xs sm:text-sm">
                <thead>
                  <tr className="bg-slate-50 dark:bg-slate-800/40 border-b border-slate-200/65 dark:border-slate-800">
                    <th className="w-1/4 p-4 text-left font-bold text-slate-900 dark:text-white">{t.parametersColumn}</th>
                    {compareList.map((scheme) => (
                      <th key={scheme.id} className="w-1/4 p-4 text-left font-bold text-slate-900 dark:text-white border-l border-slate-200/65 dark:border-slate-800 relative">
                        <div className="flex flex-col gap-2">
                          <div className="flex justify-between items-start">
                            <span className={`px-2 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wider ${
                              scheme.type === 'Central' ? 'bg-orange-50 text-orange-700 dark:bg-orange-950/20' : 'bg-blue-50 text-blue-700 dark:bg-blue-950/20'
                            }`}>
                              {scheme.type === 'Central' ? t.centralScheme : t.stateScheme}
                            </span>
                            <button
                              onClick={() => toggleCompare(scheme)}
                              className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 no-print"
                              title="Remove from comparison"
                            >
                              <X className="w-4 h-4" />
                            </button>
                          </div>
                          <span className="font-extrabold text-slate-950 dark:text-white text-sm block leading-snug">
                            {scheme.name}
                          </span>
                          {scheme.id === recommendedId && (
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 bg-gov-gold/15 text-gov-navy dark:text-amber-300 border border-gov-gold/30 rounded-full text-[10px] font-bold w-fit">
                              {t.recommendedScheme}
                            </span>
                          )}
                        </div>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {[
                    { key: 'category_name', label: t.paramLabels.category_name },
                    { key: 'department_name', label: t.paramLabels.department_name },
                    { key: 'financial_assistance_amount', label: t.paramLabels.financial_assistance_amount, format: (v) => v > 0 ? t.aidYear(v) : t.serviceBenefits },
                    { key: 'description', label: t.paramLabels.description },
                    { key: 'benefits', label: t.paramLabels.benefits },
                    { key: 'eligibility_criteria', label: t.paramLabels.eligibility_criteria },
                    { key: 'min_income', label: t.paramLabels.min_income, format: (v, item) => item.max_income < 99999999 ? t.maxIncomeLimit(item.max_income) : t.noIncomeRestriction },
                    { key: 'min_age', label: t.paramLabels.min_age, format: (v, item) => t.ageRange(item.min_age, item.max_age) },
                    { key: 'gender_restriction', label: t.paramLabels.gender_restriction, format: (v) => v === 'All' ? t.allGendersEligible : t.genderOnly(v) },
                    { key: 'required_documents', label: t.paramLabels.required_documents },
                    { key: 'application_process', label: t.paramLabels.application_process },
                    { key: 'processing_time', label: t.paramLabels.processing_time },
                    { key: 'official_website', label: t.paramLabels.official_website, format: (v) => <a href={v} target="_blank" rel="noreferrer" className="text-gov-blue hover:underline font-semibold inline-flex items-center gap-1">{v.replace('https://', '')} <ExternalLink className="w-3 h-3" /></a> },
                    { key: 'contact_details', label: t.paramLabels.contact_details }
                  ].map((row, i) => {
                    const diff = isRowDifferent(row.key);
                    return (
                      <tr
                        key={i}
                        className={`border-b border-slate-100 dark:border-slate-800 ${
                          diff ? 'bg-amber-50/20 dark:bg-amber-950/5' : ''
                        }`}
                      >
                        <td className="p-4 font-bold text-slate-800 dark:text-slate-300 align-top">
                          {row.label}
                        </td>
                        {compareList.map((scheme) => (
                          <td key={scheme.id} className="p-4 text-slate-600 dark:text-slate-300 align-top border-l border-slate-100 dark:border-slate-800 leading-relaxed">
                            {row.format ? row.format(scheme[row.key], scheme) : scheme[row.key] || 'N/A'}
                          </td>
                        ))}
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Print only watermark */}
          <div className="hidden print-only text-center text-xs text-slate-400 pt-8 border-t border-dashed mt-12">
            {t.reportWatermark(new Date().toLocaleDateString())}
          </div>
        </div>
      )}
    </div>
  );
}
